



















// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Auth`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=.;DataBase=Auth;uid=sa;pwd=123!@#qwe`
//     Schema:                 ``
//     Include Views:          `False`



using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PetaPoco;

namespace Auth
{

    public partial class AuthDB : Database
    {
        [ThreadStatic]
        static AuthDB _instance;
        private AuthDB()
            : base("Server=.;DataBase=Auth;uid=sa;pwd=123!@#qwe","System.Data.SqlClient")
        {
        }
        public static AuthDB GetInstance()
        {
            if (_instance != null)
                return _instance;
            else
                return new AuthDB();
        }
        public override void OnBeginTransaction()
        {
            if (_instance == null)
                _instance = this;
        }

        public override void OnEndTransaction()
        {
            if (_instance == this)
                _instance = null;
        }

    }




}




